package net.potm.persistence.model;
// Generated Sep 30, 2019 4:26:28 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CloudPropertiesId generated by hbm2java
 */
@Embeddable
public class AppPropertyId implements java.io.Serializable {

	private static final long serialVersionUID = -502727970617935430L;
	private String key;
	private String profile;

	public AppPropertyId() {
	}

	public AppPropertyId(String key, String profile) {
		this.key = key;
		this.profile = profile;
	}

	@Column(name = "key", nullable = false, length = 50)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key.toUpperCase();
	}

	@Column(name = "profile", nullable = false, length = 50)
	public String getProfile() {
		return this.profile;
	}

	public void setProfile(String profile) {
		this.profile = profile.toUpperCase();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AppPropertyId))
			return false;
		AppPropertyId castOther = (AppPropertyId) other;

		return ((this.getKey() == castOther.getKey())
				|| (this.getKey() != null && castOther.getKey() != null && this.getKey().equals(castOther.getKey())))
				&& ((this.getProfile() == castOther.getProfile()) || (this.getProfile() != null
						&& castOther.getProfile() != null && this.getProfile().equals(castOther.getProfile())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
		result = 37 * result + (getProfile() == null ? 0 : this.getProfile().hashCode());
		return result;
	}

}
