package net.potm.business.model;
// Generated May 16, 2019 10:46:13 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TextId generated by hbm2java
 */
@Embeddable
public class TextId implements java.io.Serializable {

	private static final long serialVersionUID = 9207632777175073948L;
	private String key;
	private String language;

	public TextId() {
	}

	public TextId(String key, String language) {
		this.key = key;
		this.language = language;
	}

	@Column(name = "key", nullable = false, length = 50)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "language", nullable = false, length = 2)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TextId))
			return false;
		TextId castOther = (TextId) other;

		return ((this.getKey() == castOther.getKey())
				|| (this.getKey() != null && castOther.getKey() != null && this.getKey().equals(castOther.getKey())))
				&& ((this.getLanguage() == castOther.getLanguage()) || (this.getLanguage() != null
						&& castOther.getLanguage() != null && this.getLanguage().equals(castOther.getLanguage())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
		result = 37 * result + (getLanguage() == null ? 0 : this.getLanguage().hashCode());
		return result;
	}

}
